# Link the C runtime statically, so shimmerble.dll needs no Visual C++ redistributable on the
# user's machine.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
